### ISSUE TITLE
Run setup.py error in linux.

### ISSUE THREAD

**Issue by kulallwang** [apache/rocketmq-client-python#38]
报错信息：
Installing collected packages: librocketmqclientpython
  Running setup.py install for librocketmqclientpython ... error
    Complete output from command /data/fulishe19/.virtualenv/rocketmq-client-python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-MQBaR1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-oBq9IE/install-record.txt --single-version-externally-managed --compile --install-headers /data/fulishe19/.virtualenv/rocketmq-client-python/include/site/python2.7/librocketmqclientpython:
    running install
    running build
    running build_py
    package init file 'src/__init__.py' not found (or not a regular file)
    running build_ext
    building 'librocketmqclientpython' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/boost -I/usr/local/include/rocketmq -I/data/.pyenv/versions/2.7.12/include/python2.7 -c src/PythonWrapper.cpp -o build/temp.linux-x86_64-2.7/src/PythonWrapper.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    src/PythonWrapper.cpp:33:45: error: ‘>>’ should be ‘> >’ within a nested template argument list
     map<CPushConsumer *, pair<PyObject *, object>> g_CallBackMap;
                                                 ^
    src/PythonWrapper.cpp: In function ‘int PyDestroyPushConsumer(void*)’:
    src/PythonWrapper.cpp:185:49: error: ‘>>’ should be ‘> >’ within a nested template argument list
         map<CPushConsumer *, pair<PyObject *, object>>::iterator iter;
                                                     ^
    src/PythonWrapper.cpp: In function ‘int PyRegisterMessageCallback(void*, PyObject*, boost::python::api::object)’:
    src/PythonWrapper.cpp:211:57: error: ‘move’ is not a member of ‘std’
         g_CallBackMap[consumerInner] = make_pair(pCallback, std::move(args));
                                                             ^
    src/PythonWrapper.cpp: In function ‘int PythonMessageCallBackInner(CPushConsumer*, CMessageExt*)’:
    src/PythonWrapper.cpp:218:49: error: ‘>>’ should be ‘> >’ within a nested template argument list
         map<CPushConsumer *, pair<PyObject *, object>>::iterator iter;
                                                     ^
    error: command 'gcc' failed with exit status 1

**Comment by ShannonDing** [comment]
@francisoliverlee Could you please check this issue?

**Comment by francisoliverlee** [comment]
@kulallwang  ‘>>’ should be ‘> >’  means wrong gcc version to build the code.
try to upgrade gcc to support c++14 .(try lastest gcc)

**Comment by 2h4dl** [comment]
@ShannonDing Did setup.py work with python3.6 in Ubuntu 16.04?

**Comment by ShannonDing** [comment]
Boost python dose not support python 3.X, you can have a try on the ctypes branch.

**Comment by vongosling** [comment]
@kulallwang ctype branch will be future for rocketmq python sdk. If you come across any problem using ctype wrapper, please let us know.
